title: "404: Security not found"
description: "Exploring cybersecurity topics for everyone"
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins (if using GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
